### ISSUE TITLE
feature beter design tokens/CSS props

### ISSUE THREAD

**Issue by GrimLink** [fylgja/fylgja#123]
Currently the design tokens are doing great.

The sizes version was to optimistic, and requires an split.
This will create more CSS vars, but is needed for other systems to work wel.

Split to;

- [x] border-radius
- [x] font-size

Also add more options for;

- ~font families~
- ~gradients (will replace the util version, later)~
- ~font styles (letter spacing, line-height, etc...)~

**Comment by allrude** [comment]
Ready in branch `feature/tokens` needs final touches and release action

**Comment by GrimLink** [comment]
Todo: finish the docs and publish the new components
