### ISSUE TITLE
Bug: .backdrop not visible on Firefox

### ISSUE THREAD

**Issue by JoshuavanGelder** [fylgja/fylgja#212]
The .backdrop class doesn't show on firefox. In my projects at least. I am not using the Alpine variant but the css variant.

Bug reports, please include:

- Operating system and version (Linux, Ubuntu 22.04.4 LTS)
- Browser and version (Firefox, 124.0.2 (64-bits))
- A width: 100%; fixed it for my encounters

**Comment by GrimLink** [comment]
Thanks for reporting this bug @JoshuavanGelder ,

I am aware of this bug happing in Firefox for some cases when using `position: absolute` with `inset: 0`.
weirdly Firefox does not take the parent width in account in those cases.

I have never seen this issue with `position: fixed`, so I tried to reproduce you issue with the `.backdrop in Firefox 124, on both Mac and Window, I don't have Linux machine so can not test it there.

In both cases the `.backdrop` worked as attended, this was tested on a blank html page with just Fylgja and some vanilla JS to create the class based dialog.
I also made one in the Tailwind Playground, knowing this something you normally work with 😜 https://play.tailwindcss.com/IPwQbF2sGn

Could you try this version and see if the bug still happens?

**Comment by JoshuavanGelder** [comment]
Hey @GrimLink

I see. In our project we set your backdrop to position absolute in our css. I didn't realise that caused the problem.

Thanks for the respones
