### ISSUE TITLE
Using / for division outside of calc() is deprecated

### ISSUE THREAD

**Issue by jissereitsma** [fylgja/fylgja#97]
When compiling sources I'm bumping into multiple deprecation warnings with text *Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0* because of lines like the following: 

```scss
margin-left: ($x / -2);
```

Reference: https://sass-lang.com/documentation/breaking-changes/slash-div

**Comment by jissereitsma** [comment]
I think this can simply be refactored into `calc($x / -2)` or so.

**Comment by GrimLink** [comment]
Weird I thought got ride of this, not sure which component is still using the older syntax.

Personally I don't have these warning anymore, using just sass, but I will investigate this.

@jissereitsma can you share me you environment details, sass version and type node or dart also if you're using webpack or something else

**Comment by GrimLink** [comment]
Ah yes the flex grid is not part of the main bundle and from version 3 of the flex grid, it is usable in the newer sass versions.
Any older version of the flex grid still uses the older node sass syntax that's why.

Moving this issue to the discussions for others to see 😉
